CREATE INDEX CATALOG_ITEMS_IDX
 ON CATALOG_ITEMS (ITEM_ID, CATALOG_ID, PARENT_ID,VALUE)
 COMPUTE STATISTICS;

commit;

CREATE INDEX CASE_PROCEEDINGS_IDX
 ON CASE_PROCEEDINGS (PROCEEDING_ID, CASE_ID, CASE_PROCEEDING_STATUS, CASE_BRANCH_ID)
 COMPUTE STATISTICS;

commit;

CREATE INDEX CAT_TRANSITION_TYPES_IDX
 ON CAT_TRANSITION_TYPES (CONDITIONAL_TYPE)
 COMPUTE STATISTICS;

commit;

CREATE INDEX CASE_ENTITY_FIELDS_IDX
 ON CASE_ENTITY_FIELDS (CASE_ENTITY_ID,OPERATOR_ID)
 COMPUTE STATISTICS;
 
commit;

CREATE INDEX CASE_PROCEEDING_FIELDS_IDX
 ON CASE_PROCEEDING_FIELDS (CASE_PROCEEDING_ID)
 COMPUTE STATISTICS;
commit;
